spring.application.name=job_application_tracker
spring.datasource.url=jdbc:postgresql://localhost:2204/jobApplicationDB
spring.datasource.username=postgres
spring.datasource.password=Pass22042010
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=YTMwYmUxOTc4NGRhZjYyNWMzMGJlMTk3ODRkYWY2MjVzZWNyZXQ0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OQ==
