spring.application.name=${SPRING_APPLICATION_NAME:job_application_tracker}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/jobApplicationDB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Pass22042010}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:YTMwYmUxOTc4NGRhZjYyNWMzMGJlMTk3ODRkYWY2MjVzZWNyZXQ0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OQ==}